WebApplication1/Controllers/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;
using PagedList;
using PagedList.Mvc;

namespace WebApplication1.Controllers
{
    public class HeaderController : Controller
    {
        // GET: Header
        public ActionResult Index(int page = 1, int pagesize = 2)
        {
            var dsHeader = HeaderBus.DanhSach().ToPagedList(page,pagesize);
            return View(dsHeader);
        }

        // GET: Header/Details/5
        public ActionResult Details(int id)
        {
            var db = HeaderBus.ChiTiet(id);
            return View(db);
        }

        // GET: Header/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Header/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Header/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Header/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Header/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Header/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Bus;
namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var dsHeader = HeaderBus.DanhSach();
            return View(dsHeader);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@model IEnumerable<NewsConnection.Header>
@{
    ViewBag.Title = "Home Page";
}

<section id="sliderSection">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <div class="slick_slider">
                @foreach (var item in Model.Reverse<NewsConnection.Header>())
                {
                    <div class="single_iteam">
                        <a href="@Url.Action("Details", "Header", new { id = item.id })"> <img src="@item.image" alt=""></a>
                        <div class="slider_article">
                            <h2><a href="@Url.Action("Details", "Header", new { id = item.id })">@item.NHeader</a></h2>
                            <p>@item.NDesc</p>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="latest_post">

                <h2><span>Latest post</span></h2>
                <div class="latest_post_container">
                    <div id="prev-button"><i class="fa fa-chevron-up"></i></div>
                    <ul class="latest_postnav">
                       @foreach (var item in Model.Reverse<NewsConnection.Header>())
                       {
                        <li>
                            <div class="media">
                                <a href="@Url.Action( "Details","Header",new { id = item.id })" class="media-left"> <img alt="" src="@item.image"> </a>
                                <div class="media-body"> <a href="@Url.Action("Details", "Header", new { id = item.id })" class="catg_title"> @item.NHeader</a> </div>
                            </div>
                        </li>
                       }                     
                    </ul>
                    <div id="next-button"><i class="fa  fa-chevron-down"></i></div>
                </div>
            </div>
        </div>
    </div>
</section>